version: '3'

services:

  guc-ical:
    image: dm/guc-ical:latest
    restart: always
    environment:
      - 'CONTAINER_TIMEZONE=Australia/Perth'
      - 'APACHE_SERVER_NAME=localhost'
      - 'PHP_DATE_TIMEZONE=Australia\/Perth'
      - 'PHP_ERROR_REPORTING=E_ALL'
      - 'PHP_DISPLAY_ERRORS=On'
      - 'PHP_VARIABLES_ORDER=EGPCS'
      - 'FEED_REGION=AU'
      - 'TIMEZONE=Australia/Perth'
    cap_add:
      - SYS_TIME
      - SYS_NICE

networks: 
  default: 
    external: 
      name: dm-docker-host